apiVersion: v1
kind: Service
metadata:
  name: content-engine
spec:
  selector:
    app: web
  # type: NodePort # public ip -> attached to the vm
  type: ClusterIP #private service
  # type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
